[package]
name = "grpc-alarms-db"
version = "0.2.0"
edition = "2024"

[dependencies]
# These dependencies are used to support Rust's async environment.

tokio = { version = "1", features = ["rt-multi-thread", "macros", "rt"] }
tracing-subscriber = { version = "0.3.22", features = ["chrono"] }
tracing = { version = "0.1.44", features = ["log"] }

# These crates are used to implement the gRPC web service.

tonic = "0.14.2"
tonic-health = "0.14.2"
tonic-prost = "0.14.2"
tonic-reflection = "0.14.2"

# These crates provide runtime support for protobufs.
prost = "0.14.1"
prost-types = "0.14.1"

# This crate provides ergonomic environment variable interaction
rust-env-var-lib = { git = "https://github.com/fermi-ad/rust-env-var-lib.git", tag = "v1.1.0" }

# This crate provides access to PostgreSQL.
rust-db-lib = { git = "https://github.com/fermi-ad/rust-db-lib.git", tag = "v3.1.1" }

# This crate generates current date and time
chrono = { version = "0.4", features = ["serde"] }

[build-dependencies]

# This crate translates protobuf source files into a Rust module.
tonic-prost-build = "0.14.2"
protoc-bin-vendored = "3.2"

[profile.release]
opt-level = 'z'
lto = true

[workspace.lints.rust]
ambiguous_negative_literals = "warn"
let_underscore_drop = "warn"
redundant_imports = "warn"
redundant_lifetimes = "warn"
unit_bindings = "warn"
unnameable_types = "warn"
unreachable_pub = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
manual_assert = "warn"
allow_attributes_without_reason = "warn"
collection_is_never_read = "warn"
comparison_chain = "warn"
elidable_lifetime_names = "warn"
empty_drop = "warn"
enum_glob_use = "warn"
equatable_if_let = "warn"
error_impl_error = "warn"
exit = "deny"
if_not_else = "warn"
if_then_some_else_none = "warn"
impl_trait_in_params = "warn"
