name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: fermi-ad/.github/.github/workflows/rust-deployment.yaml@v1
    secrets: inherit
    permissions:
      contents: read
    with:
      references-internal-git-repo: true