name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: fermi-ad/.github/.github/workflows/rust-deployment.yaml@e0c90cb1aa154991276dbdd6a4eccfd676b5208b
    secrets: inherit
    permissions:
      contents: read
    with:
      pull-git-submodules: true
      references-internal-git-repo: true