name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: fermi-ad/.github/.github/workflows/rust-deployment.yaml@f5b1570438803675367730e055d4a3e1983be9d1
    secrets: inherit
    permissions:
      contents: read
    with:
      pull-git-submodules: true
      references-internal-git-repo: true