name: Rust Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-integration.yaml@dcdbfafd8f118ba7a963890f95a0e9c50bf2d638
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
