name: Rust Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-integration.yaml@7cd9f9abf200443fbcb5362016dfbbda21c11f9d
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
