name: Rust Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-integration.yaml@fa58f6aa341d66ac40bd2ea5ef99b753b984f0d4
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
